spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev    #开发环境
  application:
    name: microservicecloud-config-yongfei-dev
    
---
spring:
  profiles: test    #测试环境
  application:
    name: microservicecloud-config-yongfei-test
    
#请保存格式为UTF-8
